name: Laravel CI/CD

on:
  push:
    branches: [ "Development", "master" ]
  pull_request:
    branches: [ "Development", "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: backend_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP Environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, zip, xml, pdo, pdo_mysql
        coverage: none

    - name: Verify Composer.json Exists
      run: ls backend/composer.json

    - name: Clean and Reinstall Dependencies
      run: |
        rm -rf backend/vendor
        composer install --no-dev --prefer-dist --working-dir=backend

    - name: Ensure Environment File Exists
      run: cp backend/.env.testing backend/.env

    - name: Generate Application Key
      run: php backend/artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 backend/storage backend/bootstrap/cache

    - name: Wait for MySQL to Fully Initialize
      run: sleep 30

    - name: Check MySQL Service Status
      run: |
        sudo service mysql status || sudo service mysql start

    - name: Debug MySQL Connection
      run: mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"

    - name: Migrate Database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: backend_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php backend/artisan migrate --force

    - name: Clear Cache & Config
      run: php backend/artisan config:clear && php backend/artisan cache:clear

    - name: Run Laravel Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: backend_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php backend/artisan test
